### ISSUE TITLE
Rule 8930 : Child Protection Plan End Date must fall within the census year

### ISSUE THREAD

**Issue by tab1tha** [data-to-insight/CIN-validator#106]
If \<CPPendDate\> (N00115) is present, then\<CPPendDate\> (N00115) must fall within [Period_of_Census] inclusive

**Comment by tab1tha** [comment]
Hi Amy, 
In case you haven't seen this yet, the text in this [pull request](https://github.com/data-to-insight/CIN-validator/pull/123) provides some additional guidelines for rules that use period of census.

**Comment by amyrichards0n** [comment]
Thank you @tab1tha

**Comment by tab1tha** [comment]
Hi @amyrichards0n  , you might find these resources useful for this issue:

- [Review notes for rule 8715](https://github.com/data-to-insight/CIN-validator/pull/147/files) . This is a step-by-step, detailed walkthrough of a similar rule.
- Full [rule_8715](https://github.com/data-to-insight/CIN-validator/blob/main/cin_validator/rules/cin2022_23/rule_8715.py) implementation file. It includes explanatory comments.
- [Rule 8545Q](https://github.com/data-to-insight/CIN-validator/blob/main/cin_validator/rules/cin2022_23/rule_8545Q.py) : It is similar to this issue and also includes two line specific to query rules. That is rules whose codes end in Q.

I hope it helps. 
See you next week !
