### ISSUE TITLE
Rule 1560Q : Please check:  Former UPN wrongly formatted

### ISSUE THREAD

**Issue by tab1tha** [data-to-insight/CIN-validator#13]
\<FormerUPN\> (N00002) where present should be in the correct format, as specified in the data table

**Comment by tab1tha** [comment]
Hi @GBurrel, are you working on this, or do you prefer that we take it up?

**Comment by tab1tha** [comment]
If you want us to take it up, could you please point us to where the specified correct format of `FormerUPN `can be found?

**Comment by GBurrel** [comment]
Hi @tab1tha  - happy for you to take it up. To be honest I'm not sure on the rule for the former IUPN. I had assumed that it would be a combination of the other separate UPN rules which have already been done for this return?

**Comment by tab1tha** [comment]
Based on this example structure `<FormerUPN> X98765432123B </FormerUPN>` gotten from the [children in need census specification ](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1025196/2022_to_2023_CIN_Census_Specification.pdf), and a similar structure in the test data, I have carved out the following guidelines:

FormerUPN should 
- be 13 characters long
- start and end with a letter
- between the edge letters must be digits.
