### ISSUE TITLE
Rule 8770Q : Please check: UPN or reason UPN missing expected for a child who is more than 5 years old

### ISSUE THREAD

**Issue by tab1tha** [data-to-insight/CIN-validator#15]
If \<ReferralNFA\> (N00112) = 0 or false and \<PersonBirthDate\> (N00066) is earlier than [\<ReferenceDate\> (N00603) minus 6 years] then either \<UPN\> (N00001) or a valid \<UPNunknown\> (N00135) should be present

**Comment by SLornieCYC** [comment]
This one is curious @tab1tha.  As far as I can see this is the only rule that tests the validity of `UPNunknown` (which I'm interpreting as "value exists in list of codes") - but it only applies if the child is over 5 years old and has an episode that wasn't NFA!

As far as I can see there are no other rules that test:
- whether `UPNunknown` is valid for children under 5
- whether `UPNunknown` is valid for children who only have NFA referrals

Am I interpreting this rule right?

**Comment by tab1tha** [comment]
@SLornieCYC I think that you are. 
This rules want to check for a valid `UPNunknown` only if the child is more than 5 years old. 


It's interesting that there are no rules that check for those other, very possible, scenarios. This rule list was generated from the official DfE guidance so if it's not here, it wasn't there (or we could've missed it, in which case we'll find out when we code the last rule and there aren't up to 108 distinct rules)
