### ISSUE TITLE
Rule 8772 : UPN unknown reason is UN7 (Referral with no further action) but at least one CIN details is a referral going on to further action 

### ISSUE THREAD

**Issue by tab1tha** [data-to-insight/CIN-validator#16]
If \<UPNunknown\> (N00135) is UN7 then all of the CIN details must have \<ReferralNFA\> (N00112) = 1 or true

**Comment by GBurrel** [comment]
Hi @tab1tha  and @willLPD2I  - appreciate it may not be possible (as you may well have other plans/work) but any chance of a quick Teams call to discuss this one? Almost there with this but (as ever) 'Assertion Error' is coming up and I'm not sure how to address it (as well as a couple of other things).  Again appreciate it may not be convenient and if so, happy till wait till next year.

**Comment by willLPD2I** [comment]
@GBurrel I'm happy to do this today, but it would make things easier for me if you can make a PR so I can look at the code on my own screen and get back to you

**Comment by GBurrel** [comment]
Will do that now @willLPD2I
