### ISSUE TITLE
Rule 8530Q : Please check:  Expected Date of Birth is outside the expected range for this census (March to December of the Census Year end)

### ISSUE THREAD

**Issue by tab1tha** [data-to-insight/CIN-validator#19]
If present \<ExpectedPersonBirthDate\> (N00098) should be between [\<ReferenceDate\> (N00603) minus 30 days] and [\<ReferenceDate\> (N00603) plus 9 months]

**Comment by phoebefryer** [comment]
Hi @willLPD2I & @tab1tha with the +6mo here is 6*30 days acceptable or does it need to be the exact 6mo and if so I think I will need an extra package, is there then a process for adding packages or just install and add it to the requirements list?

**Comment by tab1tha** [comment]
Hi @phoebefryer you can use `pd.DateOffset` like this:
`new_date = old_date + pd.DateOffset(months=9)`

Read more: https://stackoverflow.com/a/46741436/11044184

**Comment by tab1tha** [comment]
Typically, pandas methods can do most of the things that you might want to do with the date module. There is no need (so far) to import the date module. You can use pandas.
