### ISSUE TITLE
Create documentation for contributors

### ISSUE THREAD

**Issue by tab1tha** [data-to-insight/CIN-validator#273]
The docs need to contain guidelines on how to

- [x] install the tool (git clone)

run the tool as a CLI user

- [x] explain how to use the xmltocsv and run-all commands and their respective flags.

run the tool as a developer

- [x] talk about setting the path variable

- [x] guide on installing pre-commit (pre-commit install)

- [x] talk about listing out the available rules (python ... validator test), running all the tests (python ... validator list)

It can then point to a "how to contribute section" that has details of

- [x] how to join the community - contact D2I

- [x] how to open an issue if you find a bug - link to a bug template similar to the one in the 903 project.

- [x] Explanation of the various rule-type splits 

- [x] How to write the rules - link to the D2I tutorials 
https://www.datatoinsight.org/python
beginner  - https://www.datatoinsight.org/cinrules
type1 - https://www.datatoinsight.org/type-1-cin-rules
type2 - https://www.datatoinsight.org/type-2-cin-rules
type3 - https://www.datatoinsight.org/type-3-cin-rules

- [x] Finding similar rules - link to the rule pattern doc (https://github.com/data-to-insight/CIN-validator/blob/main/Documentation/RULE_PATTERNS.MD)

- [x] Structure of the input data - link to the demo-ingress jupyter notebook (https://github.com/data-to-insight/CIN-validator/blob/main/cin_validator/demo_ingress_class.ipynb)

- [x] Further exploring - link to logic demos (https://github.com/data-to-insight/CIN-validator/tree/main/Documentation/rule_logic_demos)

**Comment by tab1tha** [comment]
You can mark the ones that have been done by putting an **x** in the square brackets at the start of the task when you edit the issue description.

**Comment by tab1tha** [comment]
Can this be closed @willLPD2I

**Comment by willLPD2I** [comment]
> Can this be closed @willLPD2I

@tab1tha I'm going to do a final pass through and spell check today and will close it after that!
