### ISSUE TITLE
Rule 100 is 2022_23 specfic

### ISSUE THREAD

**Issue by willLPD2I** [data-to-insight/CIN-validator#284]
Rule 100 checks that: 
> <ReferenceDate> (N00603) must be present and must equal 2022-03-31

The rule is currently hardcoded for the current return:
```
error_date = df[ReferenceDate] != pd.to_datetime(
        "31/03/2022", format="%d/%m/%Y", errors="coerce"
    )
```

This is fine, but it  needs to be changed per return. We can't get it to rely on the input XML as it's checking that. If we get it to check the year in the rules selected where the date is checked, we won't have to re-write the rule yearly.

**Comment by tab1tha** [comment]
You're right, it is addressed here https://github.com/data-to-insight/CIN-validator/pull/229/commits/69ff896eecf2a8ead7b5c8c5273c1682d815a860 but the commit has not been merged yet

**Comment by tab1tha** [comment]
Closing this since it has been resolved.
