### ISSUE TITLE
8816 ValueError, attempt to get argmax of an empty sequence

### ISSUE THREAD

**Issue by willLPD2I** [data-to-insight/CIN-validator#294]
It looks like it's something to do with the refactor that allowed comparisons within children.

**Comment by willLPD2I** [comment]
Looking at this rule, it will not pass the Pytest when the test includes a child with multiple empty CINreferralDates and no filled CINreferralDates, which is what is causing the issue with the synthetic data. I've recreated this by adding two extra rows to the sample df:
```            
           {
                "LAchildID": "child4",
                "CINclosureDate": pd.NA,
                "CINreferralDate": pd.NA,  
                "CINdetailsID": "cinID3",
                "ReferralNFA": "0",
            },
            {
                "LAchildID": "child4",
                "CINclosureDate": pd.NA,
                "CINreferralDate": pd.NA,  
                "CINdetailsID": "cinID4",
                "ReferralNFA": "0",
            },
```

The issue is caused by trying to find the max value of an empty list, which happens in the synthetic data and *could* happen in real data being validated. Options include filling empty rows with a stand in value, as is the case in some other rule types that check across groups, and have the error id link those cells to the FE, or figure out a different way of finding the most recent values.

**Comment by tab1tha** [comment]
This is so helpful Will !
Now that you say that, it can be fixed by dropna. We can safely drop nans in CINreferralDate without affecting the logic.
