### ISSUE TITLE
Bug: Rule 2885 - flags as CPP not on ICPC date when ICPCnotRequired is true

### ISSUE THREAD

**Issue by willLPD2I** [data-to-insight/CIN-validator#310]
**Expected behavior**
If ICPCnot required is true, shouldn't flag the CPP not being on that date, as there is not one.

**Proposed fix (Optional)**
Don't fail rows with ICPCnotRequired as true

**Comment by tab1tha** [comment]
Hi @willLPD2I ,
Do check this again. Rule 2885 does not interact with the ICPC field as seen here https://github.com/data-to-insight/CIN-validator/issues/111 
It only checks that `DateOfInitialCPC` and `CPPstartDate`.

**Comment by willLPD2I** [comment]
@Tambe, you're right about my bug description, I was wrong, but there is still a bug. It's flagging ICPC and CPP as on different days when the ICPC is empty, so shouldn't be flagged.

There's a couple of weird things going on here:

CHildren hwo have no no CINdetails DateOfInitialCPC and DO have an s47 DateOfInitialCPC in the input data are shown as having neither date on the front end of the validator for some reason.

Where children have multiple CPP plans, and in one of them the DateOfInitialCPC is the same as the CPP starts date, and one isn't, it flags the one that isn't as wrong, when it's for a different plan.

Have I explained this clearly enough? I realise it's easier for me because I'm looking at the actual data

**Comment by tab1tha** [comment]
I see. 
Are you able to replicate the behaviour on test data?
If you create test data that is similar to your real data, does the rule act in the same way?.

**Comment by willLPD2I** [comment]
@tab1tha I'll start looking at that after teaching! This might be similar to https://github.com/data-to-insight/CIN-validator/pull/330 which I just did, which was merging on the wrong field, mixing up different groups.

**Comment by tab1tha** [comment]
It does seem efficient for you to do a number of these since you can see the data that fails. I'll be on QA duty then, checking that we don't change the logic as we fix.

**Comment by willLPD2I** [comment]
```
If present and if <CPPStartDate> (N00105) falls within [Period_Of_Census], then the <CPPStartDate> (N00105) should equal either:
a) a Section47 module <DateOfInitialCPC> (N00110), or
b) a CINDetails module <DateOfInitialCPC> (N00110) if there is no associated Section 47 record.
```

**Comment by willLPD2I** [comment]
The following is being wrongly failed

  ```
              <Section47>
                    <DateOfInitialCPC>SAME DATE</DateOfInitialCPC>
                </Section47>
                <ChildProtectionPlans>
                    <CPPstartDate>SAME DATE</CPPstartDate>
                </ChildProtectionPlans>

```

**Comment by willLPD2I** [comment]
After genuinely hours of staring at this wondering why it fails in production but not in the Pytest... I realised all the failing children are ones wher ehtey have multiple s47 modules, some with DateOfInitialCPC and some without. When I added an extra s47 module to a child with no date, I recreated the bug in the test environment.
