### ISSUE TITLE
22/23 validation - change 'automatic ok rules'

### ISSUE THREAD

**Issue by willLPD2I** [data-to-insight/CIN-validator#342]
The following rules been changed to automatic ‘ok’ queries: 2991Q, 8530Q, 8535Q, 8775Q and 8825Q as per https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1113325/Children_in_need_census_2023_to_2024_guide_v1.0.pdf

'Some of the validation rules that are built into COLLECT have an automatic ‘OK’ function. This means once you have checked allthe records where these rules have triggered and you are content the data is correct, you can add specific text to the return level notes field to explain the query. An algorithm is then run on the data overnight and these records are automatically authorised within the COLLECT system.'

The generic text for automatic oks is:

RULECODE: All records have been checked and can confirm that the data has been amended (where required). All remaining queries relate to assessments that were completed in the previous reporting period or where an assessment was not required

![image](https://user-images.githubusercontent.com/108789355/219588682-385090f5-b140-47f5-b9df-e90c7e11c7a7.png)
![image](https://user-images.githubusercontent.com/108789355/219588722-ef6df16a-1ee1-43c9-9400-185ec3cfb8d3.png)
![image](https://user-images.githubusercontent.com/108789355/219588808-f924f37b-8c20-4b11-8bf0-f63b4acd131a.png)
![image](https://user-images.githubusercontent.com/108789355/219588859-b21a652e-8314-4eb0-9ecd-7b6ab17e0ae2.png)
![image](https://user-images.githubusercontent.com/108789355/219588914-55f14dd2-b238-4177-ba8d-d41f367386a1.png)
![image](https://user-images.githubusercontent.com/108789355/219588988-b87989c0-7d3d-46f8-bd3d-bdbba7edb70a.png)
![image](https://user-images.githubusercontent.com/108789355/219589045-7a96f40d-e85a-43bc-b4ad-200d6300bb89.png)

**Comment by SLornieCYC** [comment]
This also applies to 22/23, per the v1.2 validation rules document. https://www.gov.uk/government/publications/children-in-need-census-2022-to-2023-specification
