### ISSUE TITLE
22/23 - Errors changed to queries

### ISSUE THREAD

**Issue by willLPD2I** [data-to-insight/CIN-validator#343]
The following rules have been changed from errors to queries: 4009, 8525, 8555, 8569, 8863, 8873 and 8897. Should be as simple as adding query to the rule types etc.

**Comment by SLornieCYC** [comment]
This also applies to 22/23, per the v1.2 validation rules document. https://www.gov.uk/government/publications/children-in-need-census-2022-to-2023-specification
