### ISSUE TITLE
Bug: Rule 1520 - Should return at child level

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/CIN-validator#365]
**Describe the bug**
Rule is currently recorded as return-level which means that the affected child IDs are not exposed to the user (i.e. have to manually trawl through dataset to find the duplicated UPN).

**Expected behavior**
The return should be converted to child-level and flag the UPN field in ChildIdentifiers where the UPN is recorded in more than one client record.  This would match the DFE CIN portal which does return the individual child level data in error lists.

**Comment by tab1tha** [comment]
Thank you @SLornieCYC 
Last [year's rule [](description](https://github.com/data-to-insight/CIN-validator/issues/9)) says that it is an LA-level rule. 
Do you mean that is has been updated to be a child-level rule in this year or is last year's description wrong?

last year: 2022/2023
this year: 2023/2-024
