### ISSUE TITLE
Bug: Rule 8863 - Duplication in Reports output

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/CIN-validator#374]
**Describe the bug**
Not quite sure what's going on here but the report output from this rule seems to return an inordinate number of rows for a single error instance compared to the DFE error report csv.  Possibly not a huge deal as easy enough to work around; but curious nonetheless.  

Even if not something solveable within this rule's coding there might be some benefit to forcing the report to only output distinct rows?

**Screenshots**
This is the output I get from one of my records in the csv export from the DFE error report:
![image](https://user-images.githubusercontent.com/89449804/223473061-0c61006f-e1e8-4581-b6f2-017e2e197ab4.png)

And this is the output I get from the same record in the csv export from the D2I CIN validator:
![image](https://user-images.githubusercontent.com/89449804/223473774-42df2227-76c7-4821-a0a1-95b610a3063a.png)

**Comment by tab1tha** [comment]
Here, a solution can be to do `df.drop_duplicates([LAchildID, rule_code, columns_affected, ROW_ID]) `when the `user_report df` is created.
Before that, could you confirm that these rows are duplicates. That is, is the LAchilD the same? (that's the only variable whose value I can't see/compare).

**Comment by SLornieCYC** [comment]
Hi @tab1tha Yes I can confirm all of those rows are for the same child.  If I do "remove duplicates" in Excel on those 18 rows (across all 8 columns in the user report) it removes 11 duplicate rows and leaves 7 unique rows.
