### ISSUE TITLE
Bug: Rule 8897 - Missing assessments with no factors

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/CIN-validator#385]
**Describe the bug**
Rule is currently ignoring completed assessments where no factors have been recorded.

**To Reproduce**
Steps to reproduce the problem, e.g.:
- Create a completed Single Assessment record (i.e. with `AssessmentAuthorisationDate`) but no `AssessmentFactors`.
- This assessment should be flagged as an error (or query - per #343).

**Expected behavior**
CAssessments with no factors recorded should be flagged, **in addition to** as assessments that use factors that don't exist in the codeset (the latter is working).

**Proposed fix (Optional)**
The number of factors needs counting per assessment and a third condition adding that returns true where countoffactors == 0.

E.g. `condition1 & (~condition2 | condition3)`

https://github.com/data-to-insight/CIN-validator/blob/dc4559d2362e0efacfe47ebb9b4b3d538c7d0094/cin_validator/rules/cin2022_23/rule_8897.py#L96-L104

**Comment by willLPD2I** [comment]
I think this should be fixed by my PR #391 which builds assessments blocks for children with no assessment factors, I'd have fixed that one much more quickly if I'd looked at this too!

**Comment by SLornieCYC** [comment]
Agree, this one looks to have been fixed by PR #391.
