### ISSUE TITLE
Bug: Python warnings in output

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/CIN-validator#393]
**Describe the bug**
Repeated warnings in output log related to the following if statements in ingress.py:

![image](https://user-images.githubusercontent.com/89449804/224675649-d35b49a3-3d2b-41d8-b095-4054cf8c51a9.png)

https://github.com/data-to-insight/CIN-validator/blob/12dbcd056b884de614dc385965b109f09d380e00/cin_validator/ingress.py#L261

https://github.com/data-to-insight/CIN-validator/blob/12dbcd056b884de614dc385965b109f09d380e00/cin_validator/ingress.py#L330

**Proposed fix (Optional)**
Seems the better syntax is to add "is not None" to the expression? E.g.

if assessment_factors **is not None**:

**Comment by tab1tha** [comment]
Good spot @SLornieCYC 
For this, it might be good to replace them with `if len(assessment_factors) > 0` as that might be more intuitive than a negative check (`if not`  statement).
