### ISSUE TITLE
Bug: Rule 1520 - Rule should ignore NULL UPN

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/CIN-validator#428]
**Describe the bug**
Rule currently flags all records that do not have a UPN value recorded as being duplicates (because they're all NULL).

**To Reproduce**
Steps to reproduce the problem, e.g.:
- Have more than one child with no UPN in `ChildIdentifiers`

**Expected behavior**
Records with no UPN should not be marked as having a duplicated UPN.

**Comment by tab1tha** [comment]
Thank you @SLornieCYC,
A fix for this will be to drop nans before checking the rule's condition.
@willLPD2I  can you take this up?.

**Comment by willLPD2I** [comment]
@tab1tha I don't have any capacity to take on any CIN stuff for the next couple of weeks outside of complete essentials and sprint planning as I've been put on a different project temporarily.

**Comment by tab1tha** [comment]
Fixed by https://github.com/data-to-insight/CIN-validator/pull/434
