### ISSUE TITLE
Bug: Rule 2889 - Errors not flagged in FE

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/CIN-validator#430]
**Describe the bug**
Some records are not being flagged as in-error when S47ActualStartDate is before CINreferralDate.  Unsure whether this is a front-end issue as I can't see anything obviously wrong with the rule coding or tests?  The records are flagged as errors in the DFE CIN portal.

**Screenshots**
![image](https://user-images.githubusercontent.com/89449804/231130658-54169323-8377-4520-82c7-58cf5ebda848.png)

**Comment by tab1tha** [comment]
How about this one @SLornieCYC

**Comment by SLornieCYC** [comment]
Yep, this one seems to be working properly now too!  Although the cell highlights on affected_fields don't seem to be working anymore (not just here, but for any rule on any client)?

**Comment by SLornieCYC** [comment]
> Could you unpick that for me
> 
> 1. Is it that the light-blue colors on cells that have issues no longer appear?
> 2. or that the deep blue cell color that you expect to appear when you click on the rule description no longer happens?
> 3. or something else?

Both 1 and 2!  Example from a different rule:

![image](https://github.com/data-to-insight/CIN-validator/assets/89449804/3ccf4c0d-5bc6-4635-9797-ab3abbfffe6b)

This should have either `UPN` or `UPNunknown` in dark blue and the other in light blue.

**Comment by tab1tha** [comment]
Thank you. 
I'll give it a look

**Comment by SLornieCYC** [comment]
> Do the colors come up now? If it doesn't, do tell me if it happens only on some children or all children.

No colours after a hard refresh in the browser (firefox).  Also tried a different browser (chrome) and no colours there either.  Seems to affect all children.  Also noticed that clicking on the errors in the list doesn't make the tables above jump to the error location (which I think it did before).

**Comment by tab1tha** [comment]
Sorry about that, @SLornieCYC 
We're not able to replicate the error on this end yet.  
I asked @willLPD2I and he is able to see the blue colours too.

**Comment by tab1tha** [comment]
Update. We've succeeded to replicate the bug but haven't solved the behaviour yet. 
I've opened an issue page for it on the frontend repo https://github.com/data-to-insight/cin-validator-fe/issues/140

**Comment by tab1tha** [comment]
Update:
The change that caused the colors to disappear [has been reverted](https://github.com/data-to-insight/cin-validator-fe/pull/142) so that the tool can remain useful in the meantime.
The side effect is that it deactivated the feature that allowed tables to have multiple rows. We are working on restoring that feature as soon as possible.
