### ISSUE TITLE
Bug: Front-end is missing data from client tables

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/CIN-validator#431]
**Describe the bug**
Not all client data from the modules is being returned on the selected client in the front-end.  E.g. I have a client who (correctly) is flagging as in-error against rule 8815 (more than one open CINdetails episode) in the front-end and error report, but the CINdetails table only shows one of the three episodes the client has!

**Expected behavior**
All client data should be returned in in the module tables in the front-end.

**Screenshots**
![image](https://user-images.githubusercontent.com/89449804/231141721-522297ab-16dc-4d05-bbd0-9bc672af886a.png)

Note that the CINdetailsID for this client shows 3 but there is only one row returned in the table.  This issue (missing data) is not specific to the CINdetails module as I have seen similar cases elsewhere too.

**Comment by tab1tha** [comment]
This has been fixed by a pull request in the frontend repo https://github.com/data-to-insight/cin-validator-fe/pull/137
Release is ongoing. Changes will be on the tool within the hour.

**Comment by SLornieCYC** [comment]
Yep! :)

**Comment by tab1tha** [comment]
woohooo
