### ISSUE TITLE
Bug: Working day rules can't connect to SSL in FE

### ISSUE THREAD

**Issue by SLornieCYC** [data-to-insight/CIN-validator#447]
**Describe the bug**
Rules using the `govuk_bank_holidays` module for working days calculations aren't working in FE.

![image](https://github.com/data-to-insight/CIN-validator/assets/89449804/e71f59b7-ae52-49a8-b1d3-f323d5e126ec)

**Comment by tab1tha** [comment]
Thank you, 
I'll check this out.

If you have a chance, do check if 8775Q is now flagging errors like it is supposed to.
We have addressed all the possible leaks, that we could find, of data between the backend and frontend.

**Comment by tab1tha** [comment]
Updating pyodide to the latest version (0.23.2) doesn't fix this.

**Comment by tab1tha** [comment]
Way forward to to pull the holiday dates from a static file that should be updated as part of the yearly ruleset update process.
