### ISSUE TITLE
Rule 8867 : CIN episode is shown as closed, however Assessment is not shown as completed

### ISSUE THREAD

**Issue by tab1tha** [data-to-insight/CIN-validator#47]
If \<CINclosureDate\> (N00102) is present then all instances of the \<Assessments\> group must include the \<AssesssmentAuthorisationDate\> (N00160)

**Comment by GBurrel** [comment]
Hi @tab1tha - not able to get this to work. I've printed the data throughout the process and it seems to be producing what I expect but I still get an Assertion Error.

**Comment by tab1tha** [comment]
Hi @GBurrel,
I'll give it a look as soon as I can.

**Comment by tab1tha** [comment]
Hi Gavin,

Unlike type 1 rules, push_type2 and push_tylpe3 create a list of objects. So, to evaluate an issue object, we'll need to get it out of the list.
I noticed that it is not rule_8867 that fails but rule_4004 (did you write this one too?. There might be a mix-up in the branches. Run "git status" in the command line to see the files that you have changed in your branch.)

Fix:
Do "issues_list = result.type3_issues" and
"issues = issues_list[0]" to get the issues object of the first thing you pushed using push_type3 in your validate function. In this case, it is the issue object created from the failing locations in the CINplanDates table.

Then you can go ahead to do "issue_table = issues.table" and the other checks.

Side note:
You can push the code as a pull request even if it is not working yet. That way, it is easier for me to see where it is failing.
Could you do that?

Best Regards,
Tambe

**Comment by GBurrel** [comment]
Hi @tab1tha - I've made the amends for the type3 rules and created the Pull request so you should now be able to view the code. I ran the 'git status' command and got 'Your branch is up to date with 'origin/Rule8867'. nothing to commit, working tree clean' so I'm not sure about rule_4004. I'm sure I've not created that one...

**Comment by willLPD2I** [comment]
Hi Both,

Sorry I haven’t responded, I’ve been away on a course.

So, as far as it helps, the version on 4004 on main was buggy for a while, but I went in and fixed it last week some time, probably after Gavin made his branch.

Gavin, to update to the working 4004, you’ll need to run: ‘git merge origin/main’ in the terminal and accept incoming changes. If that doesn’t work, let Tambe and me know.

Cheers,

William Levack-Payne (He/Him)
Data Advocate (Data to Insight)
Children’s Services

07732 824391 | ***@***.******@***.***>

**Comment by GBurrel** [comment]
Hi @willLPD2I  and @tab1tha  - not sure if I created 4004 (although it's not impossible).  I managed to create a Pull request for Rule8867 so that should be done. Do I still need to do something with 4004?

**Comment by willLPD2I** [comment]
You shouldn’t need to do anything with 4004, don’t worry!

William Levack-Payne (He/Him)
Data Advocate (Data to Insight)
Children’s Services

07732 824391 | ***@***.******@***.***>

**Comment by GBurrel** [comment]
Hi @willLPD2I and @tab1tha  - is this one complete now and can be merged?

**Comment by tab1tha** [comment]
Hi Gavin, yes it is.

**Comment by GBurrel** [comment]
Thanks @tab1tha - just trying to identify some more to do 😁

**Comment by tab1tha** [comment]
When you run this does it work?
It produces an assertion error on my end. 
I've scheduled a deep dive into the logic, for myself, later today. @GBurrel

**Comment by GBurrel** [comment]
Hi @tab1tha  - I'm getting an Assertion Error as well. To be honest I'm not sure if that was as far as I could get as I do seem to mention Assertion Errors in my first messages above.

**Comment by tab1tha** [comment]
No worries. I'll sort it out.
