### ISSUE TITLE
Rule 8816 : An open CIN episode is shown and case is not a referral with no further action, but it is not the latest episode.

### ISSUE THREAD

**Issue by tab1tha** [data-to-insight/CIN-validator#54]
If there is a \<CINdetails\> module present for the child where:

\<CINclosureDate\> (N00102) is missing; and

\<ReferralNFA\> (N00112) = false or 0

then the \<CINreferralDate\> (N00100) for this module must be the latest of all Referral Dates for that child.  

Note: This rule should be evaluated at Child-level for imported data.

**Comment by tab1tha** [comment]
Hi @willLPD2I . This is not a return level validation rule. Treat it as a simple type3 rule.
The rules that need to be flagged at LA-level have the tag "return level validation" attached to them and say so in their description. You can see in the history that I removed that tag from here.

No worries about this one. You can go ahead with it.

**Comment by willLPD2I** [comment]
@tab1tha AH okay, if you look at the issue it used to be a return level validation which is what confused me

**Comment by tab1tha** [comment]
Yep. That's on me. 
When I read the description, I classified it as such, at first, and then removed the tag when I confirmed that it wasn't that type of rule. These are the only labels for this issue now 
![image](https://user-images.githubusercontent.com/42181805/208941698-67a7d32c-d0ca-44af-8b54-bfcddd0e13d4.png)
