### ISSUE TITLE
Rule 8898 : The assessment has more than one parental or child factors with the same code

### ISSUE THREAD

**Issue by tab1tha** [data-to-insight/CIN-validator#67]
If there is more than one \<AssessmentFactors\> (N00181) for an assessment recorded, then none of the values should appear more than once for an assessment.

**Comment by PhilDeakin** [comment]
@tab1tha 
I started coding this but then I realised we might have a problem.
As it stands in the "Assessments" table we have the field "CINdetailsID"
But within the same CIN period you can have multiple assessments and within each assessment multiple AssessmentFactors.

If there were two assessments in the same CINdetailsID and they both had a factor of say "21" 
If a did a partitioned count of factors by LAChildID and CINdetailsID it would return 2 thinking it occurs twice, when it's on two separate assessments.  (Partitioning the count by LAChildID, CINdetails, AssessmentStart and AssessmentAuth would potentially solve it, but it seems a bit excessive)

Do we need some sort of AssessmentDetailID field in the Assessment table too? 

Hope my ramblings vaguely make sense.

**Comment by tab1tha** [comment]
Hi @PhilDeakin 
Apologies for the late reply. I missed this when it came in.

Yes, you're making a lot of sense. We thought about this extensively also. 
You can use the AssessmentAuthorisationDate as your AssesmentID. Ideally, we would've generated an assessmentID when converting the XML to CSVs. However, we wanted to replicate the official DfE CSV structures as seen in the DfE XML generator, so we didn't do that.

Is it a fair compromise to group assessments by AuthorisationID ?
That's what I've lightly grasped from the rules I've read so far. What do you think?

**Comment by tab1tha** [comment]
Hi @willLPD2I, let's use AssessmentActualStartDate as the identifier for assessments here.
