### ISSUE TITLE
Rule 4013 : CIN Plan end date must fall within the census year

### ISSUE THREAD

**Issue by tab1tha** [data-to-insight/CIN-validator#82]
If \<CINPlanEndDate\> (N00690) is present, then\<CINPlanEndDate\> (N00690) must fall within [Period_of_Census] inclusive

**Comment by tab1tha** [comment]
Hi @Csmyth201  , you might find these resources useful for this issue:

- [Review notes for rule 8715](https://github.com/data-to-insight/CIN-validator/pull/147/files) . This is a step-by-step, detailed walkthrough of a similar rule.
- Full [rule_8715](https://github.com/data-to-insight/CIN-validator/blob/main/cin_validator/rules/cin2022_23/rule_8715.py) implementation file. It includes explanatory comments.
- [Rule 8545Q](https://github.com/data-to-insight/CIN-validator/blob/main/cin_validator/rules/cin2022_23/rule_8545Q.py) : It is similar to this issue and also includes two line specific to query rules. That is rules whose codes end in Q.

I hope it helps. 
See you next week !

**Comment by Csmyth201** [comment]
Hi @tab1tha, 
Thanks for the extra references, they have been really helpful. 

Unfortunately, it keeps failing with this error (invalid literal for int() with base 10: '31/03/2022') which I think is to do with the data type being passed into the make_census_period function in the test section. I have tried copying and pasting previous code (8715) and changing the tables names etc so suit my rule, but it's still throwing the same error. Has others come across this problem? 

I think only I am able to see my code space, so I have committed the code (if thats the right term) from my codespace, calling it NOT WORKING rule4013 so you can see it. 

Thanks for the help :)
