### ISSUE TITLE
Rule 4016 : A CIN Plan has been reported as open at the same time as a Child Protection Plan.  

### ISSUE THREAD

**Issue by tab1tha** [data-to-insight/CIN-validator#85]
The \<CINPlanStartDate\> (N00689) for any CIN Plan group cannot fall within either:  \<CPPstartDate\> (N00105) or \<CPPendDate\> (N00115); or \<CPPstartDate\> and \<ReferenceDate\> (N00603) if \<CPPendDate\> is not present - for any CPP group; unless \<CINPlanStartDate\> is equal to \<CPPendDate\> for this group

**Comment by SLornieCYC** [comment]
@tab1tha Don't think this is a type1 rule?- Involves multiple CIN modules (CPP and CIN plan).
